[ENG-5988] Zotero Implementation for CitationInterface
CenterForOpenScience/gravyvalet pull request #109
Opened 2024-09-09 12:01 UTC by ly-mariia

- implemented **Zotero API** and all necessary citations support;

ticket: https://openscience.atlassian.net/jira/software/c/projects/ENG/boards/145?assignee=712020%3A8af272bd-2e97-46c2-b42c-1c046bb6bb57&selectedIssue=ENG-5988

2024-09-09 15:25 UTC, brianjgeiger requested changes
Overall, I think it looks good, from the perspective of someone who's never implemented anything in GV before. There's a couple of nits, a question that may lead to some work, and a request to not mess with the initial migration anymore.

2024-09-09 15:25 UTC, brianjgeiger commented on addon_service/migrations/0001_initial.py
> +# Generated by Django 4.2.7 on 2024-09-09 11:49
Can we not merge into the initial migration anymore? Now that we are on staging, we should be just making normal forward migrations from now on.

2024-09-10 12:27 UTC, ly-mariia commented on addon_imps/citations/zotero_org.py
> +                    f"Failed to fetch key information. Status code: {response.status}"
Yes, the `Zotero API `does send useful `messages` along with their `status codes`, especially when an `error` occurs. These messages are included in the body of the response and provide additional details about the issue encountered.
I will add them!

2024-09-10 14:01 UTC, brianjgeiger approved these changes
Looks good, thanks!

2024-09-10 14:02 UTC, brianjgeiger commented
Well, except for the PR migration conflict.

2024-09-10 14:08 UTC, ly-mariia commented
TY, now trying to fix the conflict of migrations

2024-09-13 17:40 UTC, merged