- OwncloudAPI Storage Implementation
CenterForOpenScience/gravyvalet pull request #127
Opened 2024-10-11 14:05 UTC by sh-andriy

Implemented **`Owncloud Storage Addon`**. For more details look at ticket **`ENG-6043`**

2024-10-30 09:29 UTC, opaduchak requested changes

2024-10-30 09:29 UTC, opaduchak commented on addon_service/external_service/storage/models.py
> +            return SupportedFeatures(0)
can you elaborate on this change please?

2024-10-30 09:29 UTC, opaduchak commented on addon_imps/storage/owncloud.py
> +
it seems that these lines are nearly identical to 134-146, if it isn't much trouble, please make it more DRY

2024-10-30 09:29 UTC, opaduchak commented on addon_imps/storage/owncloud.py
> +        </d:propfind>"""
Maybe extract this into Enum or at least keep them separate from Imp as they impose some clutter

2024-11-05 12:21 UTC, opaduchak commented on addon_imps/storage/owncloud.py
> +            raise ValueError("displayname not found in response")
duplication of `_parse_current_user_principal`

2024-11-05 13:15 UTC, opaduchak requested changes

2024-11-06 15:54 UTC, brianjgeiger approved these changes
XML interface? What a pain!

2024-11-06 15:54 UTC, merged