[ENG-6569] |  wb_config fix for Owncloud and Bitbucket + Owncloud Implementation Connection Fix bug
CenterForOpenScience/gravyvalet pull request #167
Opened 2024-11-26 12:39 UTC by sh-andriy

[ENG-6569] |  wb_config fix for Owncloud and Bitbucket + Owncloud Implementation Connection Fix bug

2024-11-26 13:47 UTC, opaduchak commented on addon_imps/storage/bitbucket.py
> +        }
I don't see any usages for this method

2024-11-26 13:48 UTC, opaduchak commented on addon_imps/storage/bitbucket.py
> +        self.token = auth_result_extras.get("token")
I don't see the necessity to assign this attribute, moreover this class would be destroyed after response is returned

2024-11-26 13:52 UTC, opaduchak commented on addon_service/common/waterbutler_compat.py
> +                return {"token": _creds_data.access_token, "host": host_url}
this quirk is only characteristic to owncloud, no need to add this for token auth

2024-11-28 13:50 UTC, opaduchak requested changes

2024-11-28 13:50 UTC, opaduchak commented on addon_imps/storage/owncloud.py
> +        return "default-username"
nit: make this a property

2024-11-28 13:50 UTC, opaduchak commented on addon_service/common/waterbutler_compat.py
> +        wb_config = async_to_sync(imp.build_wb_config)()
I think this may cause performance issues, 
I'd implement some sort of caching for `_config_for_waterbutler` method

2024-11-28 16:21 UTC, opaduchak approved these changes
Great work!

2024-12-02 13:45 UTC, brianjgeiger approved these changes

2024-12-02 13:45 UTC, merged