[ENG-6650] Remote Computing / Boa addon
CenterForOpenScience/gravyvalet pull request #171
Opened 2024-12-02 15:23 UTC by felliott

* Add infrastructure for new type of addons, `remote-computing`.
* Add implementation of first remote-computing service, Boa.
* GLEEP! I forgot to regenerate the migration. The migration is correct, but the order is wrong!

2024-12-05 14:34 UTC, opaduchak reviewed
Great work!
I've left some questions, but I am not sure whether any changes are required

2024-12-05 14:34 UTC, opaduchak commented on addon_service/credentials/models.py
>              return None
I suppose that this except clause is redundant

2024-12-05 14:34 UTC, opaduchak commented on addon_service/credentials/models.py
>              return None
But on the other hand, authorized account property accounts for all addon types

2024-12-16 18:13 UTC, brianjgeiger requested changes
One potential change from me.

2024-12-16 18:14 UTC, brianjgeiger commented on addon_service/addon_operation_invocation/views.py
> +            else:  # computing
Same comment here.

2024-12-17 11:11 UTC, opaduchak requested changes
Seems good,
But I believe you have missed removing one extra field from configured compute addon serializer

2024-12-17 11:11 UTC, opaduchak commented on addon_service/configured_addon/computing/serializers.py
> +    root_folder = serializers.CharField(required=False, allow_blank=True)
I beleive this field is redundant for computing addons

2024-12-17 11:16 UTC, opaduchak commented on addon_service/configured_addon/computing/views.py
> +    serializer_class = ConfiguredComputingAddonSerializer
If you are planning to fetch credentials from `gravyvalet` for computing addons (in this PR), you should add action for credential fetching similar to `ConfiguredStorageAddonViewSet`

2024-12-17 15:09 UTC, brianjgeiger approved these changes
I'm good once Oleh is happy with this. Also, based on [this conversation](https://github.com/CenterForOpenScience/osf.io/pull/10851/files#r1883955318), are we setting the `wb_key` properly in this PR?

2024-12-18 15:16 UTC, opaduchak approved these changes
I have nothing to add, LGTM!

2024-12-18 18:23 UTC, merged