[ENG-6672] |  fixed bug when workspace item_type selected for Bitbucket
CenterForOpenScience/gravyvalet pull request #181
Opened 2024-12-12 15:29 UTC by sh-andriy

`[ENG-6672]` |  fixed bug when workspace item_type selected for Bitbucket

[ENG-6672]: https://openscience.atlassian.net/browse/ENG-6672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-16 15:49 UTC, opaduchak requested changes
Please adjust boolean flags a litte, rather than that everything is good

2024-12-16 15:49 UTC, opaduchak commented on addon_imps/storage/bitbucket.py
> +            can_be_root_val = item_type_value == storage.ItemType.FOLDER
Waterbutler doesn't support setting folder inside repositoey as bibucket root (as with all git-like addons)

2024-12-16 15:49 UTC, opaduchak commented on addon_imps/storage/bitbucket.py
> +                    can_be_root=True,
this is default behaviour, you needn't have explicitly stated this

2024-12-16 15:49 UTC, opaduchak commented on addon_imps/storage/bitbucket.py
> +                    can_be_root_val = item_type_value == storage.ItemType.FOLDER
Waterbutler doesn't support setting folder inside repository as bitbucket root (as with all git-like addons)

2024-12-16 15:49 UTC, opaduchak commented on addon_imps/storage/bitbucket.py
> +                        can_be_root=True,
this is default behaviour, you needn't have explicitly stated this

2024-12-17 15:55 UTC, opaduchak approved these changes
LGTM

2024-12-17 16:13 UTC, brianjgeiger approved these changes

2024-12-17 16:14 UTC, merged